/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airensoft_aviplayer_app_AVIPlayer */

#ifndef _Included_com_airensoft_aviplayer_app_AVIPlayer
#define _Included_com_airensoft_aviplayer_app_AVIPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airensoft_aviplayer_app_AVIPlayer
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_airensoft_aviplayer_app_AVIPlayer
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_airensoft_aviplayer_app_AVIPlayer
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_airensoft_aviplayer_app_AVIPlayer
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_airensoft_aviplayer_app_AVIPlayer
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_close
  (JNIEnv *, jclass, jlong);

JNIEXPORT jboolean JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_render
  (JNIEnv *, jclass, jlong, jobject);

JNIEXPORT jboolean JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_glrender
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_init
  (JNIEnv *, jclass, jlong);


JNIEXPORT void JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_initSurface
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT void JNICALL Java_com_airensoft_aviplayer_app_AVIPlayer_free
  (JNIEnv *, jclass, jlong);


#ifdef __cplusplus
}
#endif
#endif
