/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/bitmap.h>
/* Header for class com_packtpub_CameraView */

#ifndef _Included_com_airensoft_livecamera_app_CameraView
#define _Included_com_airensoft_livecamera_app_CameraView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_packtpub_CameraView
 * Method:    decode
 * Signature: (Landroid/graphics/Bitmap;[B)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_livecamera_app_CameraView_decode(JNIEnv * pEnv, jclass  pClass, jobject pTarget, jbyteArray pSource);

#ifdef __cplusplus
}
#endif
#endif