/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airensoft_store_app_Store */

#ifndef _Included_com_airensoft_store_app_Store
#define _Included_com_airensoft_store_app_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airensoft_store_app_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_airensoft_store_app_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_airensoft_store_app_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_store_app_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_airensoft_store_app_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_airensoft_store_app_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_airensoft_store_app_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_store_app_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_airensoft_store_app_Store
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_com_airensoft_store_app_Store_getColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_airensoft_store_app_Store
 * Method:    setColor
 * Signature: (Ljava/lang/String;Ljava/lang/jobject;)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_store_app_Store_setColor
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
