/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airensoft_jni01_app_HelloJNI */

#ifndef _Included_com_airensoft_jni01_app_HelloJNI
#define _Included_com_airensoft_jni01_app_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airensoft_jni01_app_HelloJNI
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_airensoft_jni01_app_HelloJNI_getHelloString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
