/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airensoft_jnithreads_app_NDKModule */

#ifndef _Included_com_airensoft_jnithreads_app_MainActivity
#define _Included_com_airensoft_jnithreads_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airensoft_jnithreads_app_NDKModule
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_jnithreads_app_MainActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_airensoft_jnithreads_app_NDKModule
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_jnithreads_app_MainActivity_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_airensoft_jnithreads_app_NDKModule
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_jnithreads_app_MainActivity_nativeWorker
  (JNIEnv *, jobject, jint, jint);


JNIEXPORT void JNICALL Java_com_airensoft_jnithreads_app_MainActivity_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
