/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airensoft_nativeegldemo_app_NativeEGL */

#ifndef _Included_com_airensoft_nativeegldemo_app_NativeEGL
#define _Included_com_airensoft_nativeegldemo_app_NativeEGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airensoft_nativeegldemo_app_NativeEGL
 * Method:    nativeOnStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_nativeegldemo_app_NativeEGL_nativeOnStart
  (JNIEnv *, jclass);

/*
 * Class:     com_airensoft_nativeegldemo_app_NativeEGL
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_nativeegldemo_app_NativeEGL_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     com_airensoft_nativeegldemo_app_NativeEGL
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_nativeegldemo_app_NativeEGL_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     com_airensoft_nativeegldemo_app_NativeEGL
 * Method:    nativeOnStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_airensoft_nativeegldemo_app_NativeEGL_nativeOnStop
  (JNIEnv *, jclass);

/*
 * Class:     com_airensoft_nativeegldemo_app_NativeEGL
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_airensoft_nativeegldemo_app_NativeEGL_nativeSetSurface
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
